import HomePage from '@/containers/HomePage'
import { useSidebarContext } from '@/contexts/SidebarContext'
import clsx from 'clsx'
import Head from 'next/head'

export default function Home() {
  const { isOpen, handleChange } = useSidebarContext()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main id="body-container">
        <div
          id="index-container"
          className={clsx(
            'mx-auto flex max-w-6xl justify-center font-epilogue',
            {
              ['z-20 h-full w-full overflow-hidden bg-black/60']: isOpen,
            },
          )}
          onClick={handleChange}
        >
          <HomePage />
        </div>
      </main>
    </>
  )
}
