import HomePage from '@/containers/HomePage'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main id="body">
        <div
          id="index-container"
          className="mx-auto flex max-w-6xl justify-center font-epilogue xs:h-[calc(100vh-4rem)]"
        >
          <HomePage />
        </div>
      </main>
    </>
  )
}
